---
title: White plaque disease - Compilation of rawdata
author: Andia Chaves Fonnegra, Bernd Panassiti
date: '08.23.2016; last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output: 
  pdf_document: 
    number_sections: yes
    toc: yes
header-includes: \usepackage{graphicx}
email: \email{}
---

```{r setup, include=FALSE, warnings=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```

# Introduction
Compilation of raw data. 


# Data

# Joint model
## Loading data 
```{r}
rm(list=ls(all=TRUE))
# Load settings
source('r-code/00_settings.R')


# load data & libraries
White <- read.csv("data/Rawdata_WP_forBayesian.csv", header = TRUE)
ls(White)
dim(White)

```


Clean data from NAs. I used the NULL function to get rid of orbital Velocities column 
```{r cleaning NAs,  eliminating the minimum data}
#Eliminate Orbital Velocites Variable due to too many NAs
White$Orbital_Velocity <- NULL
head(White)

#check how many rows have NAs
row.has.na <- apply(White, 1, function(x){any(is.na(x))})

#to obtain a logical vector with values denoting whether there is any NA in a row. 
#To see how many rows you'll have to drop:
sum(row.has.na)

#Eliminate the rows with NAs
White.filtered <- White[!row.has.na,]
#checking new lenght of the file, it should be 155 rows x 30 columns (double check excel files no NAs sheet)
dim(White.filtered) #good 155rows  x 30 columns
head(White.filtered, n=14)

```


Check data for correlations
```{r}
#Eliminate Month-text column, as we have a Monthnumber column
White.filtered$Month <- NULL

#Subset the data for environmental variables
Env1 <- data.frame(White.filtered[,4:9]) #Six Environmental variables at a time
Env2<- data.frame(White.filtered[,10:14]) # Four more environmental variables
Env3<- data.frame(White.filtered[c(4:6,10:14)]) #Three variables from Env1 and five from Env2
Env4<- data.frame(White.filtered[c(7:9,10:14)]) #Other three variables from Env1 and five from Env2

head(Env3)

#Exploring data summary
#summary(White.filtered)

#use ggpairs to check possible correlations between all 11 environmental variables

library(GGally)
ggpairs(Env1) # Fig Env1. correlated salinity with depth and density with depth
ggpairs(Env2) # Fig En2. No correlation rain and turbidity not clear correlated when using all the stations shallow and deep
ggpairs(Env3) #conductivity and temperature are correlated, and density and temperature

ggpairs(Env4)

#Correlated environmental variables include:


```

Loading libraries
```{r load Libraries if required}

if(!require(formatR))
{
  install.packages("formatR", repos = mir)
  require(formatR)
}

if(!require(StanHeaders)) 
{
  install.packages("StanHeaders", repos = mir)
  require(StanHeaders)
}

if(!require(rstan))
{
  install.packages("rstan", repos = mir)
  require(rstan)
}

if(!require(MCMCpack)) # rwish function
{
  install.packages("MCMCpack", repos = mir)
  require(MCMCpack)
}

if(!require(modeest)) 
{
  install.packages("modeest", repos = mir)
  require(modeest)
} 

if(!require(IDPmisc))
{
  install.packages("IDPmisc", repos = mir)
  require(IDPmisc)
} 

if(!require(ggplot2)) 
{
  install.packages("ggplot2", repos = mir)
  require(ggplot2)
}
if(!require(shinystan))
{
  install.packages("shinystan", repos = mir)
  require(shinystan)
}
if(!require(qtlcharts))
{
  install.packages("qtlcharts", repos = mir)
  require(qtlcharts)
}
```




Data preparation.All environmental data is scaled due to difference in units, this to avoid
adding more variability in the analysis
```{r data_preparation}

White$Chl_sca   <- scale(White$Chlorophyll)
White$Cond_sca    <- scale(White$Conductivity)
White$Den_sca    <- scale(White$Density)
White$DepCTD_sca    <- scale(White$Depth_CTD)
White$Oxy_sca   <- scale(White$Oxygen)
White$Sal_sca    <- scale(White$Salinity)
White$Turb_sca    <- scale(White$Turbidity)
White$Depth-tran_sca    <- scale(White$Depth_disease_transect)
White$Temp_sca    <- scale(White$Temperature)
White$DHW_sca    <- scale(White$Max_DHW)
White$Rain_sca    <- scale(White$Rainfall)


Year=White$Year
Month=White$Month_number
Season=White$Season
Station=White$Station_name
Depth=White$Depth_disease_transect

##Environmental variables include temperature and rainfall
enviroselection = c(10:20) # to select environmental variables
```


# Data as a list
```{r}
Season=c(sort(rep(1:4,4)))
dataList = list (
        TotalObservedcolonies = White$Ntot,
        Diseasedcolonies = White$ill,
        nWP = length(White$Plague),
        
        Cor = White$Cor,

        Environment = White[12:(12-1+length(enviroselection))], # Temp, Chlorophyll, Salinity, Turbidity
        nEnvi = length(enviroselection),

        Season = White$Season,
        Year = White$Year,
        Station = White$Station,
        nSeason = length(unique(Season)),
        nYear= length(unique(Year)),
        nStation = length(unique(Station))
        
)
```

