---
title: White plaque disease - Appendix A - Biological and Environmental Variables Included
author: Andia Chaves Fonnegra, Bernd Panassiti
date: '08.23.2016; last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output: 
  pdf_document: 
    number_sections: yes
    toc: yes
header-includes: \usepackage{graphicx}
email: \email{}
---


```{r setup, include=FALSE, warnings=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```


# Introduction
RStan code to predict prevalences of White PLague disease in corals in the US-Virgin Islands using GLMM evaluated in a Bayesian framework.  


# Data

# Joint model
## Loading data 
```{r}
rm(list=ls(all=TRUE))
# Load settings
library(ROCR)
source('r-code/00_settings.R')

# load data & libraries
White <- read.csv("data/DeepSeasonEnviBio.csv", header = TRUE)
```

#Loading librarie
```{r load Libraries if required}

if(!require(formatR))
{
  install.packages("formatR", repos = mir)
  require(formatR)
}

if(!require(StanHeaders)) 
{
  install.packages("StanHeaders", repos = mir)
  require(StanHeaders)
}

if(!require(rstan))
{
  install.packages("rstan", repos = mir)
  require(rstan)
}

if(!require(MCMCpack)) # rwish function
{
  install.packages("MCMCpack", repos = mir)
  require(MCMCpack)
}

if(!require(modeest)) 
{
  install.packages("modeest", repos = mir)
  require(modeest)
} 

if(!require(IDPmisc))
{
  install.packages("IDPmisc", repos = mir)
  require(IDPmisc)
} 

if(!require(ggplot2)) 
{
  install.packages("ggplot2", repos = mir)
  require(ggplot2)
}
if(!require(shinystan))
{
  install.packages("shinystan", repos = mir)
  require(shinystan)
}
if(!require(qtlcharts))
{
  install.packages("qtlcharts", repos = mir)
  require(qtlcharts)
}
```

## Data preparation
```{r data_preparation}
<<<<<<< HEAD
scale(White$Cor)
scale(White$Temp)
scale(White$Chl)
scale(White$Sal)
scale(White$Tur)
scale(White$Plague)
scale(White$DHW)
=======
White$TempScaled   <- scale(White$Temp)
White$ChlScaled    <- scale(White$Chl)
White$SalScaled    <- scale(White$Sal)
White$TurScaled    <- scale(White$Tur)
>>>>>>> origin/master

Year=White$Year
Season=White$Season
Station=White$Station
##Environmental variables include temperature and rainfall
<<<<<<< HEAD
enviroselection = c(5:9) # to select environmental variables

bioselection = c(4:4) #to select biological variables
=======
enviroselection = c(12:15) # to select environmental variables
>>>>>>> origin/master
```


# Data as a list
```{r}
Season=c(sort(rep(1:4,4)))
dataList = list (
        TotalObservedcolonies = White$Ntot,
        Diseasedcolonies = White$ill,
        nWP = length(White$Plague),
        
        Cor = White$Cor,

        Environment = White[12:(12-1+length(enviroselection))], # Temp, Chlorophyll, Salinity, Turbidity
        nEnvi = length(enviroselection),

        Season = White$Season,
        Year = White$Year,
        Station = White$Station,
        nSeason = length(unique(Season)),
        nYear= length(unique(Year)),
        nStation = length(unique(Station))
        
)
```



## Model definition

```{r define_model}
# Define model

model.bn.Wplague <- '
data {
// counters
<<<<<<< HEAD
int<lower=0> nWP;  //number of White Plague cases, int=integer  and non negative >0 
int<lower=0> nEnvi;  //number of environmental variables
int<lower=0> nBio;  //number of biological variables
int<lower=0> nSeason; //number of Seasons sampled

// predictors
matrix[nWP, nEnvi] Environment;
matrix[nWP, nBio] Biological;
int<lower=0> Season[nWP];
=======
int<lower=0> nWP;      // number of White Plague cases, int=integer  and non negative >0 
int<lower=0> nEnvi;    // number of environmental variables
int<lower=0> nSeason;  // number of Seasons sampled
int<lower=0> nStation; // number of Stations sampled
int<lower=0> nYear;    // number of Years sampled

// predictors
matrix[nWP, nEnvi] Environment;
real Cor [nWP]; 
int<lower=0> Season[nWP];
int<lower=0> Station[nWP];
int<lower=0> Year[nWP];
>>>>>>> origin/master

// response
int<lower=0> TotalObservedcolonies [nWP]; // Total number of coral colonies (cases)
int<lower=0> Diseasedcolonies [nWP];      // number of diseased coral colonies (successes)
}

parameters {
// parameters that will be used in the model should be defined here
// these will be saved and printed with the output

real b0;                        // intercept
vector[nEnvi] parEnvironment;   // Environmental-level
real parCor;                    // total % of coral species (biotic variable)

real <lower=0> tauSeason;
vector[nSeason] v_raw;
<<<<<<< HEAD
=======

real <lower=0> tauStation;
vector[nSeason] u_raw;

real <lower=0> tauYear;
vector[nSeason] y_raw;
>>>>>>> origin/master
}

transformed parameters {
// generation of derived parameters from parameters above should be defined here
// these will be saved and printed with the output

vector[nSeason] v;    // Season effects
vector[nStation] u;   // Station effects
vector[nYear] y;      // Year effects


<<<<<<< HEAD
vector[nSeason] v; //Season effects
=======
>>>>>>> origin/master
real RealDisease[nWP];
vector[nWP] mu;          // model error

for (h in 1:nSeason){
v[h] = v_raw[h]*(tauSeason);
}

<<<<<<< HEAD
for (h in 1:nSeason){
v[h] = v_raw[h]*(tauSeason);
=======
for (j in 1:nStation){
u[j] = u_raw[j]*(tauStation);
>>>>>>> origin/master
}

for (k in 1:nYear){
y[k] = y_raw[k]*(tauYear);
}

for( i in 1:nWP ) {
<<<<<<< HEAD
mu[i] = v[Season[i]];
RealDisease[i]  = (b0  + Environment[i] * parEnvironment + Biological[i] * parBiological + mu[i]);
=======
mu[i] = v[Season[i]] + u[Station[i]]+ y[Year[i]];
RealDisease[i]  = (b0  + Environment[i] * parEnvironment + Cor[i] * parCor + mu[i]);
>>>>>>> origin/master
}
}

model{
// This is area for describing the model including the priors and likelihood
// This is the only place where sampling can be done within Stan
// All data and parameters used in this section must be defined above

// Fixed effects priors
b0 ~ normal(0, 10 ); //
parEnvironment ~ normal(0 , 10 );
parCor ~ normal(0 , 10 );

//Hyperpriors
tauSeason ~ inv_gamma(0.001, 0.001);    
<<<<<<< HEAD

=======
tauStation ~ inv_gamma(0.001, 0.001);    
tauYear ~ inv_gamma(0.001, 0.001); 
>>>>>>> origin/master

//Random effects priors
v_raw ~ normal(0, 1);
u_raw ~ normal(0, 1);
y_raw ~ normal(0, 1);

#specification of the model-Binomial-logit model
Diseasedcolonies ~ binomial_logit(TotalObservedcolonies,RealDisease);
}
'
```

## Running the model
```{r test_run,echo=FALSE,eval=FALSE}
stan.white <- stan(model_code = model.bn.Wplague, data = dataList, iter = 5000, chains = 1,refresh=1,thin=1)
```

```{r model_run,eval=FALSE}
time <- proc.time()
set.seed(2016)
stan.season<- stan(model_code = model.bn.Wplague, data = dataList, iter = 30000, chains = 4,refresh=1)
(proc.time() - time)/60/60
```
6

# Session info
```{r}
devtools::session_info()
```


```{r-To save the output file}

library(lattice)
trellis.device("pdf", file = paste("Figures_Season/", today, "_Output_rstan.pdf",
sep = ""), width = 14, height = 7)
plot(stan.white)
dev.off()

```



```{r ploting from stan to ggmcmc}
print(stan.season)
plot(stan.season)

library(ggmcmc)
library(coda)

#this one extracts everything 
s <- rstan::extract(stan.season, inc_warmup=FALSE, permuted=FALSE) 
#this one extracts only some functions

s <- mcmc.list(mcmc(s[,1,-4]), mcmc(s[,2,-4]), mcmc(s[,3,-4]), mcmc(s[,4,-4]))
S <- ggs(s) 
#This function makes all types of graphs in one, takes a while to be process
ggmcmc(S)

#for specific parameters. But is not running
s <- rstan::extract(stan.white, pars = 'v_raw', permuted = TRUE)$parEnvironment 
s <- do.call(mcmc.list, alply(s[,,-4], 2, mcmc))

```


```{r Plot extracting from rstan by christophergandrud/StanCat}
#To use ggmcmc#the rstan::extract, specify that is extracted from rstan procedure and not from dpylr
library(plyr)
#This is to Install Stan Caterpillar StanCat to build caterpillar graphs from Stan
#devtools::install_github('christophergandrud/StanCat')
#stan_caterpillar(obj, pars, pars_labels = NULL, hpd = TRUE,
#  order_medians = TRUE, horizontal = TRUE, alpha_bounds = 0.3)
#For months
StanCat::stan_caterpillar(stan.white, pars = 'v_raw\\[.*\\]', pars_labels = c("Feb/12", "Mar/12", "Apr/12", "May/12", "Aug/12", "Sep/12", "Oct/12", "Nov/12", "Dec/12", "Feb/13", "Mar/13", "May/13", "Jul/13", "Aug/13", "Nov/13", "Dec/13"))

#Seasons
StanCat::stan_caterpillar(stan.season, pars = 'v_raw\\[.*\\]', pars_labels = c("Dry", "Dry-Wet", "Wet", "Wet Heat Stress"))
#Biological Variables
StanCat::stan_caterpillar(stan.season, pars = 'parBiological\\[.*\\]', pars_labels = "% Coral")
#Environmental Variables
<<<<<<< HEAD
StanCat::stan_caterpillar(stan.season, pars = 'parEnvironment\\[.*\\]', pars_labels= c("Chlorophyll", "Salinity", "Turbidity", "Temperature", "DHW"))
=======
StanCat::stan_caterpillar(stan.season, pars = 'parEnvironment\\[.*\\]', pars_labels= c("Chlorophyll", "Salinity", "Turbidity", "Temperature"))
>>>>>>> origin/master


```


```{r extract and plot with shiny -Stan}
launch_shinystan(stan.white)
```



