---
title: "Creation of white_working_data"
author: "Andia Chaves Fonnegra"
date: "7/18/2017"
output: pdf_document
---

# Introduction
This file is to prepare the data before feeding it into the model.
Here I scaled data and do shanges on the working data


# Data preparation

```{r setup, include=FALSE, warnings=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```


## Loading data
```{r}
# load data & libraries - Loading Raw data file as r.data
load(file="Data/Whiteplague_rawdata.rdata")
ls()
#check data
dim(Whiteplague_rawdata)
head(Whiteplague_rawdata)

load('data/whiteplaque_rawdata.RData')

#check data
White <- WhitePlaque
ls(White)
dim(White)
head(White)
```


## Data preparation
All environmental data is scaled due to difference in units, this to avoid adding more variability in the analysis
```{r data_preparation}
Whiteplague_rawdata$Chl_sca   <- scale(Whiteplague_rawdata$Chlorophyll)
Whiteplague_rawdata$Cond_sca    <- scale(Whiteplague_rawdata$Conductivity)
Whiteplague_rawdata$Den_sca    <- scale(Whiteplague_rawdata$Density)
Whiteplague_rawdata$DepCTD_sca    <- scale(Whiteplague_rawdata$Depth_CTD)
Whiteplague_rawdata$Oxy_sca   <- scale(Whiteplague_rawdata$Oxygen)
Whiteplague_rawdata$Sal_sca    <- scale(Whiteplague_rawdata$Salinity)
Whiteplague_rawdata$Turb_sca    <- scale(Whiteplague_rawdata$Turbidity)
Whiteplague_rawdata$Depth_tran_sca  <- scale(Whiteplague_rawdata$Depth_transect)
Whiteplague_rawdata$Temp_sca    <- scale(Whiteplague_rawdata$Temperature)
Whiteplague_rawdata$DHW_sca    <- scale(Whiteplague_rawdata$Max_DHW)
Whiteplague_rawdata$Rain_sca    <- scale(Whiteplague_rawdata$Rainfall)

White$Chl_sca   <- scale(White$Chlorophyll)
White$Cond_sca    <- scale(White$Conductivity)
White$Den_sca    <- scale(White$Density)
White$DepCTD_sca    <- scale(White$Depth_CTD)
White$Oxy_sca   <- scale(White$Oxygen)
White$Sal_sca    <- scale(White$Salinity)
White$Turb_sca    <- scale(White$Turbidity)
White$Depth_tran_sca  <- scale(White$Depth_transect)
White$Temp_sca    <- scale(White$Temperature)
White$DHW_sca    <- scale(White$Max_DHW)
White$Rain_sca    <- scale(White$Rainfall)

#Simplifying syntax of factors (Year, Depth, Month, Season, Station) to use in the model
Year=Whiteplague_rawdata$Year
Month=Whiteplague_rawdata$Month_number
Season=Whiteplague_rawdata$Season
Station=Whiteplague_rawdata$Station_name
Depth=Whiteplague_rawdata$Depth_disease_transect

##Selecting Environmental variables to use in the model
enviroselection = c(32:42) # to select environmental variables. ``{r}
enviroselection

#Sorting the data frame so Months can be in numerical order
Whiteplague_working_data<-Whiteplague_rawdata[order(Whiteplague_rawdata$Month_12),]
Whiteplague_working_data

```

## Saving data
```{r}
#Save working data  file with data already scaled/ and or transformed to be used by the model
save(Whiteplague_working_data,file="Data/Whiteplague_working_data.rdata")
ls()
#check data
ls(Whiteplague_working_data)
dim(Whiteplague_working_data)
head(Whiteplague_working_data)

#count how many sampling per month we have in total
library(plyr)
count(Whiteplague_working_data$Month_12)
```

