---
title: "Environmental drivers of white plague disease on shallow and mesophotic coral reefs, U.S. Virgin Islands"
subtitel: "Residual diagnosis"
author: "Andia Chaves-Fonnegra, Bernd Panassiti, Tyler B. Smith, Elizabeth Brown, Elizabeth Clemens, Moriah Sevier, and Marilyn Brandt"
date: 'created: 25/07/2017, last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output: pdf_document
---

```{r setup, include=FALSE, warnings=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```


# Introduction


# Data


# Model


## Loading data
```{r}
rm(list=ls(all=TRUE))
load(file="data/whiteplaque_workingdata.Rdata")
```



#From Panassiti et al., 2016
#Extraction of residuals from the posterior of a stan-object
#At first rstan package is loaded and the entire posterior with all parameters extracted

```{r}
library(rstan)
posterior<-extract(stan.white2,inc_warmup=F,permute=F) # extraction of posterior
```

Extraction of posterior predictive simulations.
```{r}
# real White Plague Prevalence Predictions are simulated (predictions generated in the
# Generated quantities block of the model code)
modelPredictions<-apply(posterior, MARGIN=1:2, FUN = function(draw)
draw[grepl("^Real White Plague Prevalence Predictions[\\[]",names(draw))])

# combine 4 chains
simulatedPredictedWP <- NULL
simulatedPredictedWP <- cbind(modelPredictions[,,1], modelPredictions[,,2],
modelPredictions[,,3], modelPredictions[,,4]) # combining chains
```


Extraction of median model predictions on the response scale
```{r}
# Real WP prevalence Predictions (are the predictions on the linear scale which are
# transformed in a 2. step to be on the response scale (inv.logit()))
modelPredictions <- NULL
modelPredictions<-apply(posterior, MARGIN=1:2, FUN = function(draw)
draw[grepl("^Real White Plague Prevalence Predictions[\\[]",names(draw))])
# combine 4 chains
predictionsLinearWP <- NULL
predictionsLinearWP <- cbind(modelPredictions[,,1], modelPredictions[,,2],
modelPredictions[,,3], modelPredictions[,,4]) # combining chains
predictionsResponseWPMedian <-
inv.logit(as.vector(apply(predictionsLinearPathogen, 1, median)))*trapsResponse$HoTotal
```

Residual diagnosis
```{r}
#devtools::install_github(repo = "DHARMa", username = "florianhartig",
#subdir = "DHARMa", dependencies = T, build_vignettes = TRUE)
library(DHARMa)
WP_DHARMaResponse <- createDHARMa(
simulatedResponse = simulatedPredictedWP,
observedResponse = observedWP,
fittedPredictedResponse = predictionsResponseWPMedian,
integerResponse = T) # interger correction function
plotSimulatedResiduals(simulationOutput = WP_DHARMaResponse)
testSpatialAutocorrelation(WP_DHARMaResponse , x = trapCoords$st_x,
y = trapCoords$st_y)

```

