---
title: White plaque disease - Compilation of rawdata
author: Andia Chaves Fonnegra, Bernd Panassiti
date: '08.23.2016; last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output: 
  pdf_document: 
    number_sections: yes
    toc: yes
header-includes: \usepackage{graphicx}
email: \email{}
---

```{r setup, include=FALSE, warnings=FALSE}
library(knitr)
opts_knit$set(root.dir='../')                     # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center',                # aligns all figures
                echo=TRUE,                        # shows r-code
                message=FALSE,                    # suppresses library outputs
                warnings=FALSE,                   # suppresses library outputs
                tidy=TRUE,  # prevents the source code from running off a pdf page
                dev='pdf')                        # pdf device
```

# Introduction
Compilation of raw data. 


# Data

# Joint model
## Loading data 
```{r}
rm(list=ls(all=TRUE))
# Load settings
source('r-code/00_settings.R')
<<<<<<< Updated upstream
=======

# load data & libraries
White <- read.csv("data/Rawdata_WP_forBayesian.csv", header = TRUE)
ls(White)
dim(White)
>>>>>>> Stashed changes
```


Clean data from NAs. I used the complete.cases function to get rid all of incomplete rows and columns
```{r}
<<<<<<< Updated upstream
WhitePlaque <- read.table("data/Rawdata_WhitePlaque.csv",header=T,sep=",")
```
=======
#Eliminate Orbital Velocites Variable due to too many NAs
White <- White[!(is.na(White$Orbital_Velocity)) | !(is.na(White$Depth_disease_transect)),]
head(White, n=5)
#check how many rows have NAs
row.has.na <- apply(White, 1, function(x){any(is.na(x))})

#to obtain a logical vector with values denoting whether there is any NA in a row. 
#To see how many rows you'll have to drop:
sum(row.has.na)
>>>>>>> Stashed changes

White.filtered <- White[!row.has.na,]
#checking new lenght of the file, it should be 155 (double check excel files no NAs sheet)
White
head(White.filtered, n=5)

<<<<<<< Updated upstream
```{r}
save(
  WhitePlaque,
  file="data/whiteplaque_rawdata.RData"
)
=======
#Eliminate rows with NA
dim(White.filtered)
>>>>>>> Stashed changes
```

